{% set name = "kim-convergence" %}
{% set version = "0.0.3" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 607ba1ccfc5bd95c15c6d8fdbb1ee2c515b57ab61baa6dbfa3e8adb89d968f0c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=45
    - versioneer >=0.29
    - kim-edn >1.4.0
  run:
    - python >={{ python_min }}
    - kim-edn >1.4.0
    - numpy >1.16
    - scipy
    - joblib

test:
  requires:
    - python {{ python_min }}
  imports:
    - kim_convergence

about:
  home: https://github.com/openkim/kim-convergence
  license:  LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: KIM-CONVERGENCE utility module
  description: |
    KIM-CONVERGENCE utility module.
    The objective is to make it as easy as possible to help in automatic
    equilibration detection & run length control.

extra:
  recipe-maintainers:
    - yafshar
